<?
//This is auto-generated file by FileFunc::saveVarsToFile()
//DO NOT EDIT!

$occupation=array(
1=>array(
'id'=>'1',
'name_ru'=>'Арт директор',
'name_ua'=>'Арт директор',
'name_en'=>'Art Director',
'name_url'=>'art_director',
'name'=>'Арт директор'),
3=>array(
'id'=>'3',
'name_ru'=>'Ассистент фотографа',
'name_ua'=>'Асистент фотографа',
'name_en'=>'Assistant photographer',
'name_url'=>'assistant_photographer',
'name'=>'Ассистент фотографа'),
5=>array(
'id'=>'5',
'name_ru'=>'Визажист/Стилист',
'name_ua'=>'Візажист/Стиліст',
'name_en'=>'Make-up artist/Stylist',
'name_url'=>'makeup_artist_stylist',
'name'=>'Визажист/Стилист'),
7=>array(
'id'=>'7',
'name_ru'=>'Модель',
'name_ua'=>'Модель',
'name_en'=>'Model',
'name_url'=>'model',
'name'=>'Модель'),
2=>array(
'id'=>'2',
'name_ru'=>'Профессиональный фотограф',
'name_ua'=>'Професійний фотограф',
'name_en'=>'Professional photographer',
'name_url'=>'professional_photographer',
'name'=>'Профессиональный фотограф'),
4=>array(
'id'=>'4',
'name_ru'=>'Рекламное агентство',
'name_ua'=>'Рекламне агентство',
'name_en'=>'Advertising Agency',
'name_url'=>'advertising_agency',
'name'=>'Рекламное агентство'),
8=>array(
'id'=>'8',
'name_ru'=>'Свободный художник',
'name_ua'=>'Вільний художник',
'name_en'=>'Freelancer',
'name_url'=>'freelancer',
'name'=>'Свободный художник'),
6=>array(
'id'=>'6',
'name_ru'=>'Фотолюбитель',
'name_ua'=>'Фотолюбитель',
'name_en'=>'Amateur photographer',
'name_url'=>'amateur_photographer',
'name'=>'Фотолюбитель'));