--
-- Table structure for table `exif`
--

DROP TABLE IF EXISTS `exif`;
CREATE TABLE `exif`(
  `PhotoId` int(11) unsigned NOT NULL,
  `Make` varchar(255) default NULL,
  `Model` varchar(255) default NULL,
  `ImageDescription` varchar(255) default NULL,
  `ExposureTime` varchar(255) default NULL,
  `FNumber` varchar(255) default NULL,
  `ISOSpeedRatings` int(11) unsigned default NULL,
  `FocalLength` varchar(255) default NULL,
  `MaxApertureValue` varchar(255) default NULL,
  `XResolution` varchar(255) default NULL,
  `YResolution` varchar(255) default NULL,
  `ResolutionUnit` tinyint(3) unsigned NOT NULL,
  `Software` varchar(255) default NULL,
  `DateTime` varchar(255) default NULL,
  `DateTimeOriginal` varchar(255) default NULL,
  `DateTimeDigitized` varchar(255) default NULL,
  `SceneType` tinyint(3) unsigned NOT NULL,
  `Orientation` tinyint(3) unsigned NOT NULL,
  `MeteringMode` tinyint(3) unsigned NOT NULL,
  `ExposureMode` tinyint(3) unsigned NOT NULL,
  `ExposureProgram` tinyint(3) unsigned NOT NULL,
  `Flash` tinyint(3) unsigned NOT NULL,
  `FlashEnergy` varchar(255) default NULL,
  `WhiteBalance` tinyint(3) unsigned NOT NULL,
  `LightSource` tinyint(3) unsigned NOT NULL,
  `ColorSpace` varchar(255) default NULL,
  `SensingMethod` tinyint(3) unsigned NOT NULL,
  `FocalLengthIn35mmFilm` varchar(255) default NULL,
  `Contrast` tinyint(3) unsigned NOT NULL,
  `Saturation` tinyint(3) unsigned NOT NULL,
  `Sharpness` tinyint(3) unsigned NOT NULL,
  `Compression` tinyint(3) unsigned NOT NULL,
  `ExposureBiasValue` varchar(255) default NULL,
  `ExifImageWidth` varchar(255) default NULL,
  `ExifImageLength` varchar(255) default NULL,
  `FlashPixVersion` varchar(255) default NULL,
  `ExifVersion` varchar(255) default NULL,
  `CustomRendered` tinyint(3) unsigned NOT NULL,
  `FileName` varchar(255) default NULL,
  `FileDateTime` int(11) unsigned default NULL,
  `FileSize` int(11) unsigned default NULL,
  `FileType` tinyint(3) unsigned NOT NULL,
  `MimeType` varchar(255) default NULL,
  `IsColor` tinyint(3) unsigned NOT NULL,
  `ByteOrderMotorola` varchar(255) default NULL,
  `CCDWidth` varchar(255) default NULL,
  `SectionsFound` varchar(255) default NULL,
  `FocalPlaneResolutionUnit` tinyint(3) unsigned NOT NULL,
  `FocalPlaneXResolution` varchar(255) default NULL,
  `FocalPlaneYResolution` varchar(255) default NULL,
  `SubsecTime` varchar(255) default NULL,
  `SubSecTimeDigitized` varchar(255) default NULL,
  `SubSecTimeOriginal` varchar(255) default NULL,
  `UserComment` varchar(255) default NULL,
  `FileSource` tinyint(3) unsigned NOT NULL,
  `DigitalZoomRatio` varchar(255) default NULL,
  `SceneCaptureType` tinyint(3) unsigned NOT NULL,
  `GainControl` tinyint(3) unsigned NOT NULL,
  `LensType` varchar(255) default NULL,
  `OwnerName` varchar(255) default NULL,
  `FirmWareVersion` varchar(255) default NULL,
  `SubjectDistanceRange` tinyint(3) unsigned NOT NULL,
  `SubjectDistance` varchar(255) default NULL,
  `PhotometricInterpretation` tinyint(3) unsigned NOT NULL,
  `Artist` varchar(255) default NULL,
  `BatteryLevel` varchar(255) default NULL,
  `BitsPerSample` varchar(255) default NULL,
  `BrightnessValue` varchar(255) default NULL,
  `CFAPattern` varchar(255) default NULL,
  `CFARepeatPatternDim` varchar(255) default NULL,
  `ComponentsConfiguration` varchar(255) default NULL,
  `CompressedBitsPerPixel` varchar(255) default NULL,
  `Copyright` varchar(255) default NULL,
  `DeviceSettingDescription` varchar(255) default NULL,
  `DocumentName` varchar(255) default NULL,
  `ExifIfdPointer` varchar(255) default NULL,
  `ExposureIndex` varchar(255) default NULL,
  `FillOrder` tinyint(3) unsigned NOT NULL,
  `HalftoneHints` tinyint(3) unsigned NOT NULL,
  `ImageUniqueID` varchar(255) default NULL,
  `InterColorProfile` varchar(255) default NULL,
  `InteroperabilityIFDPointer` varchar(255) default NULL,
  `InterOperabilityIndex` varchar(255) default NULL,
  `InteroperabilityVersion` varchar(255) default NULL,
  `NewSubfileType` varchar(255) default NULL,
  `ExtraSamples` tinyint(3) unsigned NOT NULL,
  `OECF` varchar(255) default NULL,
  `PixelXDimension` varchar(255) default NULL,
  `PixelYDimension` varchar(255) default NULL,
  `PlanarConfiguration` tinyint(3) unsigned NOT NULL,
  `Predictor` tinyint(3) unsigned NOT NULL,
  `PrimaryChromaticities` varchar(255) default NULL,
  `ReferenceBlackWhite` varchar(255) default NULL,
  `RelatedImageFileFormat` varchar(255) default NULL,
  `RelatedImageLength` varchar(255) default NULL,
  `RelatedSoundFile` varchar(255) default NULL,
  `RowsPerStrip` varchar(255) default NULL,
  `SampleFormat` tinyint(3) unsigned NOT NULL,
  `SamplesPerPixel` tinyint(3) unsigned NOT NULL,
  `SpatialFrequencyResponse` varchar(255) default NULL,
  `SpectralSensitivity` varchar(255) default NULL,
  `StripByteCounts` varchar(255) default NULL,
  `StripOffsets` varchar(255) default NULL,
  `SubIFDs` varchar(255) default NULL,
  `SubjectArea` varchar(255) default NULL,
  `SubjectLocation` tinyint(3) unsigned NOT NULL,
  `Threshholding` tinyint(3) unsigned NOT NULL,
  `TransferFunction` tinyint(3) unsigned NOT NULL,
  `TransferRange` varchar(255) default NULL,
  `WhitePoint` varchar(255) default NULL,
  `GPSVersionID` varchar(255) default NULL,
  `InfoIFDPointer` varchar(255) default NULL,
  `GPSLatitudeRef` char(1) default NULL,
  `GPSLatitude` varchar(255) default NULL,
  `GPSLongitudeRef` char(1) default NULL,
  `GPSLongitude` varchar(255) default NULL,
  `GPSAltitudeRef` tinyint(3) unsigned NOT NULL,
  `GPSAltitude` varchar(255) default NULL,
  `GPSTimeStamp` varchar(255) default NULL,
  `GPSSatellites` varchar(255) default NULL,
  `GPSStatus` varchar(255) default NULL,
  `GPSMeasureMode` varchar(255) default NULL,
  `GPSSpeedRef` char(1) default NULL,
  `GPSSpeed` varchar(255) default NULL,
  `GPSTrackRef` char(1) default NULL,
  `GPSTrack` varchar(255) default NULL,
  `GPSImgDirectionRef` char(1) default NULL,
  `GPSImgDirection` varchar(255) default NULL,
  `GPSDestLatitudeRef` char(1) default NULL,
  `GPSDestLatitude` varchar(255) default NULL,
  `GPSDestLongitudeRef` char(1) default NULL,
  `GPSDestLongitude` varchar(255) default NULL,
  `GPSDestBearingRef` char(1) default NULL,
  `GPSDestBearing` varchar(255) default NULL,
  `GPSDestDistanceRef` char(1) default NULL,
  `GPSDestDistance` varchar(255) default NULL,
  PRIMARY KEY(`PhotoId`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE utf8_general_ci;